Description: Create a Bucket in AWS S3

Resources:
  BucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-tmabigdata
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True